### ISSUE TITLE
请求出错？下载不成功，用docker跑的

### ISSUE THREAD

**Issue by xingbaoliang** [QiuChenlyOpenSource/QQFlacMusicDownloader#160]
<img width="749" alt="image" src="https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/27947669/ceaf81e5-b337-4ca8-83aa-33fb493c9d5a">

**Comment by lancer-wang** [comment]
docker 教程过期了，那个人的镜像不更新了，需要自行编译镜像

**Comment by lancer-wang** [comment]
git clone XXXX
然后cd 到根目录
docker build -t 自定义镜像名称 .   (注意结尾的点也要）
然后docker  命令那边 image 换成你自定义镜像名称

**Comment by xingbaoliang** [comment]
<img width="1672" alt="image" src="https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/27947669/1a7b3b31-062e-49ee-9426-5054c00a4cb9">


> docker 教程过期了，那个人的镜像不更新了，需要自行编译镜像
docker打包失败了，本地跑起来搜索选择qq音乐是可以下载的。

**Comment by xingbaoliang** [comment]
> <img alt="image" width="1672" src="https://user-images.githubusercontent.com/27947669/273795082-1a7b3b31-062e-49ee-9426-5054c00a4cb9.png">
> > docker 教程过期了，那个人的镜像不更新了，需要自行编译镜像
> > docker打包失败了，本地跑起来搜索选择qq音乐是可以下载的。

我更换了镜像，项目中的镜像地址下载Flask失败

**Comment by fejich** [comment]
简单试了下
把项目源码拉到本地，映射到 Docker 容器里边
能正常跑，下载了好几首歌都没遇到问题

```
---
version: "3"
services:
  musicdownloader:
    image: python:3.11-slim-buster
    container_name: QQFlacMusicDownloader
    tty: true
    volumes:
      - ./workspace:/workspace
    network_mode: bridge
    ports:
      - 8899:8899
    command: sh -c "cd /workspace && pip3 install --no-cache-dir --upgrade pip -i https://mirrors.bfsu.edu.cn/pypi/web/simple && pip3 install --no-cache-dir -r requirements.txt -i https://mirrors.bfsu.edu.cn/pypi/web/simple && python3 MainServer.py"
    restart: unless-stopped
```
