### ISSUE TITLE
一段时间后再去搜索下载歌曲会失败

### ISSUE THREAD

**Issue by VectorZhao** [QiuChenlyOpenSource/QQFlacMusicDownloader#87]
# 环境
docker部署
```
version: "3"
services:
  downloader:
    image: registry.cn-hangzhou.aliyuncs.com/music_downloader/qq_flac_music_downloader
    container_name: music
    network_mode: host
    volumes:
      -  /mnt/share_nfs/Music:/workspace/music
    ports:
      - "8899:8899"
    restart: always
```
# 问题
一段时间后进去web搜索歌曲进行下载，虽然会弹窗提示下载成功，但是实际并没有下载。重启容器再去下载，此时可一成功下载音乐。
